- name: Create Azure Storage account
  azure_rm_deployment:
    state: present
    subscription_id: "{{ azure_subscription_id }}"
    resource_group_name: "{{ azure_resource_group }}"
    location: "West Europe"
    parameters:
      storageAccountType:
        value: Standard_LRS
      location:
        value: "{{ azure_resource_region }}"
    template_link: 'https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-storage-account-create/azuredeploy.json'
  register: output_azure_storage

- name: Run integration Tests
  shell : | 
    inspec exec integrationtests/ditesting -t azure:// --controls='/sampleinfra[0-9]/'

